"""empty message

Revision ID: fa3acdb9e2ae
Revises: c19f62a73cb7
Create Date: 2018-07-27 08:16:20.432651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3acdb9e2ae'
down_revision = 'c19f62a73cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone2', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone2')
    # ### end Alembic commands ###
